### ISSUE TITLE
ADD THE SAFER_CHECK ARGUMENT EVERYWHERE

### ISSUE THREAD

**Issue by gael-millot** [safer-r/ggcute#2]
See the .docx document.
Copy-paste below.

1.	ADD THE SAFER_CHECK ARGUMENT
1.1.	AT THE BEGINNING OF ALL SAFER FUNCTIONS
#' @title two_colons_check
#' @description
#' Verify that all the functions used inside a function are all referenced by their package attribution. For instance: base::mean()
#' @param x a function name, written without quotes and brackets.
#' @param safer_check Single logical value. Perform some "safer" checks (see https://github.com/safer-r)? If TRUE, checkings are performed before main code running: 1) R classical operators (like "<-") not overwritten by another package because of the R scope and 2) required functions and related packages effectively present in local R lybraries. Set to FALSE if this fonction is used inside another "safer" function to avoid pointless multiple checkings.
#' @returns 
#' A message indicating the missing ::
#' 
#'- §problem: logical. Is there any problem detected?
#' 
#'- §text: message indicating the details of the problem, or the absence of problem.
#' 
#' - §object.name: value of the data.name argument (i.e., name of the checked object if provided, NULL otherwise).
#' @details
[todo.docx](https://github.com/safer-r/ggcute/files/14836953/todo.docx)

#' - #' More precisely, two_colons_check() verifies that all the strings before an opening bracket "(" are preceeded by "::"
#' 
#' - The regex used is: "\\b[a-zA-Z.]{1}[a-zA-Z0-9._]+\\b(?= *\\()"
#'  
#' - The following R operators using bracket are not considered: "function", "if", "for", "while" and "repeat"
    # Dot at first position is removed (dur to stringr::str_extract_all() function ).
    # Function with dot at last position are not detected
#' 
#'  
#' @examples
#' two_colons_check(mean)
#' 
#' @export
two_colons_check <- function(
    x, 
    safer_check = TRUE
){

    # DEBUGGING
    # x = saferDev::get_message ; safer_check = TRUE
    # package name
    package.name <- "saferDev"
    # end package name
    # function name
    function.name <- paste0(as.list(match.call(expand.dots = FALSE))[[1]], "()") # function name with "()" paste, which split into a vector of three: c("::()", "package()", "function()") if "package::function()" is used.
    if(function.name[1] == "::()"){
        function.name <- function.name[3]
    }
    arg.names <- names(formals(fun = sys.function(sys.parent(n = 2)))) # names of all the arguments
    arg.user.setting <- as.list(match.call(expand.dots = FALSE))[-1] # list of the argument settings (excluding default values not provided by the user)
    # end function name
    # critical operator checking
    if(safer_check == TRUE){
        .base_op_check(external.function.name = function.name)
    }
    # end critical operator checking
    # check of lib.path
    # end check of lib.path
    # check of the required function from the required packages

    # end check of the required function from the required packages
    # end package checking

If this section 
    # check of the required function from the required packages
    # end check of the required function from the required packages

is not empty, then:

    if(safer_check == TRUE){
        .pack_and_function_check(
            fun = c(
                "ggplot2::ggplot_build"
            ),
            lib.path = NULL,
            external.function.name = function.name
        )
    }

1.2.	IN ANY SAFER<...>:: FUNCTION
Now, we must check all saferDev::, saferGraph::, etc. functions used inside other functions and add the safer_check = FALSE.
For example, in safer-r/ggcute/R/ggpalette, replace this line 74:
    tempo <- saferDev::arg_check(data = n, class = "integer", length = 1, double.as.integer.allowed = TRUE, neg.values = FALSE, fun.name = function.name) ; base::eval(ee)
By:
    tempo <- saferDev::arg_check(data = n, class = "integer", length = 1, double.as.integer.allowed = TRUE, neg.values = FALSE, fun.name = function.name, safer_check = FALSE) ; base::eval(ee)

**Comment by gael-millot** [comment]
Moved to safer-r

**Comment by gael-millot** [comment]
Cannot move to safer-r. So I will copy-paste this issues in every safer-r repositories.

**Comment by Tintin2710** [comment]
1. arg_test .R:  
- [ ] transforme arg_check() par saferDev::arg_check(),
- [ ] fun_gg_boxplot est remplacé par ggbox
- [ ] ajoute package names avant les fonctions
- [ ] ADD THE SAFER_CHECK ARGUMENT

**Comment by Tintin2710** [comment]
2. arg_check.R:
- [ ] ajoute les packagenames avant les fonctions
- [ ] ADD THE SAFER_CHECK ARGUMENT

**Comment by Tintin2710** [comment]
3. env_check.R:
- [ ]  ADD THE SAFER_CHECK ARGUMENT
- [ ] modifie l'ordre

**Comment by Tintin2710** [comment]
get_message.R:
- [ ] ajoute packagenamas avant les fonctions
- [ ] modifie l'ordre
- [ ] ADD THE SAFER_CHECK ARGUMENT

**Comment by Tintin2710** [comment]
is_function_here:
- [ ] ADD THE SAFER_CHECK ARGUMENT
- [ ] ajoute packagenamas avant les fonctions
- [ ] modifie l'ordre

**Comment by Tintin2710** [comment]
is_package_here.R:
- [x] ajoute les packagenames avant les fonctions
- [x] ADD THE SAFER_CHECK ARGUMENT
- [x] modifie l'ordre

**Comment by Tintin2710** [comment]
report.R:
- [x] ajoute les packagenames avant les fonctions
- [x] ADD THE SAFER_CHECK ARGUMENT
- [x] modifie l'ordre

**Comment by Tintin2710** [comment]
done
